[package]
name = "Server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.46", features = ["full"] }
hyper = { version = "0.14", features = ["full"] }
once_cell = "1.18"
lru = "0.8"
dashmap = "5"
anyhow = "1"
